/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tech.auju.display;


import com.tech.auju.implementation.PembelianImpl;
import com.tech.auju.util.DocumentMaker;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractListModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author sora
 */
public class Main extends javax.swing.JFrame {

    private final int CURRENT_STOCK = 0;
    private final int EMPTY_STOCK = 1;
    private final int RETUR = 2;
    
    private PembelianImpl pi;
    
    public Main() { 
        initComponents();
    }
    /**
     * Creates new form Main
     */
    public Main(String user) {
        // REAL MAIN
        initComponents();
        initTable();
        lblHello.setText("Hello " + user + "!");
        lstBeli1.setModel(pi.getListModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHello = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        lblEmptyStocks = new javax.swing.JLabel();
        lblPurchStatus = new javax.swing.JLabel();
        lblCurrentStocks = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        pnlCurrStocks = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCurrent = new javax.swing.JTable();
        btnClose = new javax.swing.JButton();
        pnlEmptyStocks = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstBeli1 = new javax.swing.JList();
        btnBeli = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstBeli2 = new javax.swing.JList();
        btnPesan = new javax.swing.JButton();
        lblTotPengeluaran = new javax.swing.JLabel();
        pnlRetur = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblRetur = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnLogOut = new javax.swing.JMenuItem();
        mnExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pembelian v.2.0");

        lblHello.setText("Hello ");

        pnlMenu.setBackground(new java.awt.Color(245, 240, 51));

        lblEmptyStocks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmptyStocks.setText("Empty Stocks");
        lblEmptyStocks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEmptyStocksMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEmptyStocksMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEmptyStocksMouseEntered(evt);
            }
        });

        lblPurchStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPurchStatus.setText("Return Stocks");
        lblPurchStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPurchStatusMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPurchStatusMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPurchStatusMouseEntered(evt);
            }
        });

        lblCurrentStocks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurrentStocks.setText("Current Stocks");
        lblCurrentStocks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCurrentStocksMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCurrentStocksMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCurrentStocksMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addComponent(lblCurrentStocks, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmptyStocks, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPurchStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblEmptyStocks, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblPurchStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblCurrentStocks, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tblCurrent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No.", "Bahan", "Jumlah Bahan", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCurrent);

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCurrStocksLayout = new javax.swing.GroupLayout(pnlCurrStocks);
        pnlCurrStocks.setLayout(pnlCurrStocksLayout);
        pnlCurrStocksLayout.setHorizontalGroup(
            pnlCurrStocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
            .addGroup(pnlCurrStocksLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnClose))
        );
        pnlCurrStocksLayout.setVerticalGroup(
            pnlCurrStocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCurrStocksLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        lstBeli1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstBeli1);

        btnBeli.setText(">>");
        btnBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeliActionPerformed(evt);
            }
        });

        btnDel.setText("<<");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(lstBeli2);

        btnPesan.setText("Pesan");
        btnPesan.setEnabled(false);
        btnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanActionPerformed(evt);
            }
        });

        lblTotPengeluaran.setText("Total pengeluaran : Rp 0");

        javax.swing.GroupLayout pnlEmptyStocksLayout = new javax.swing.GroupLayout(pnlEmptyStocks);
        pnlEmptyStocks.setLayout(pnlEmptyStocksLayout);
        pnlEmptyStocksLayout.setHorizontalGroup(
            pnlEmptyStocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmptyStocksLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEmptyStocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBeli, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(btnDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEmptyStocksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotPengeluaran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPesan)
                .addContainerGap())
        );
        pnlEmptyStocksLayout.setVerticalGroup(
            pnlEmptyStocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmptyStocksLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(btnBeli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlEmptyStocksLayout.createSequentialGroup()
                .addGroup(pnlEmptyStocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEmptyStocksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesan)
                    .addComponent(lblTotPengeluaran))
                .addContainerGap())
        );

        tblRetur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No.", "Tanggal", "Daftar Pemesanan", "Status Pembayaran"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblRetur);

        jButton3.setText("Make Document");

        javax.swing.GroupLayout pnlReturLayout = new javax.swing.GroupLayout(pnlRetur);
        pnlRetur.setLayout(pnlReturLayout);
        pnlReturLayout.setHorizontalGroup(
            pnlReturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
            .addGroup(pnlReturLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3))
        );
        pnlReturLayout.setVerticalGroup(
            pnlReturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReturLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlCurrStocks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlEmptyStocks, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlRetur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlCurrStocks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlEmptyStocks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlRetur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(pnlCurrStocks, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(pnlEmptyStocks, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(pnlRetur, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu1.setText("Settings");

        mnLogOut.setText("Log out");
        mnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLogOutActionPerformed(evt);
            }
        });
        jMenu1.add(mnLogOut);

        mnExit.setText("Exit");
        mnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        mnAbout.setText("About");
        mnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAboutActionPerformed(evt);
            }
        });
        jMenu2.add(mnAbout);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHello, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHello)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCurrentStocksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCurrentStocksMouseEntered
        // TODO add your handling code here: 241, 234, 51
        
        lblCurrentStocks.setBackground(new Color(241, 234, 51));
        lblCurrentStocks.setOpaque(true);
    }//GEN-LAST:event_lblCurrentStocksMouseEntered

    private void lblCurrentStocksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCurrentStocksMouseExited
        // TODO add your handling code here: 245, 240, 51
        lblCurrentStocks.setBackground(new Color(245, 240, 51));
        lblCurrentStocks.setOpaque(false);
    }//GEN-LAST:event_lblCurrentStocksMouseExited

    private void lblEmptyStocksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmptyStocksMouseEntered
        // TODO add your handling code here:
        lblEmptyStocks.setBackground(new Color(241, 234, 51));
        lblEmptyStocks.setOpaque(true);
    }//GEN-LAST:event_lblEmptyStocksMouseEntered

    private void lblEmptyStocksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmptyStocksMouseExited
        // TODO add your handling code here:
        lblEmptyStocks.setBackground(new Color(245, 240, 51));
        lblEmptyStocks.setOpaque(false);
    }//GEN-LAST:event_lblEmptyStocksMouseExited

    private void lblPurchStatusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPurchStatusMouseEntered
        // TODO add your handling code here:
        lblPurchStatus.setBackground(new Color(241, 234, 51));
        lblPurchStatus.setOpaque(true);
    }//GEN-LAST:event_lblPurchStatusMouseEntered

    private void lblPurchStatusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPurchStatusMouseExited
        // TODO add your handling code here:
        lblPurchStatus.setBackground(new Color(245, 240, 51));
        lblPurchStatus.setOpaque(false);
    }//GEN-LAST:event_lblPurchStatusMouseExited

    private void lblEmptyStocksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmptyStocksMouseClicked
        // TODO add your handling code here:
        changeMenu(EMPTY_STOCK);
    }//GEN-LAST:event_lblEmptyStocksMouseClicked

    private void lblCurrentStocksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCurrentStocksMouseClicked
        // TODO add your handling code here:
        changeMenu(CURRENT_STOCK);
    }//GEN-LAST:event_lblCurrentStocksMouseClicked

    private void lblPurchStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPurchStatusMouseClicked
        // TODO add your handling code here:
        changeMenu(RETUR);
    }//GEN-LAST:event_lblPurchStatusMouseClicked

    private void btnBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeliActionPerformed
        // TODO add your handling code here:
        if(lstBeli1.isSelectionEmpty() == false) {
            pi.setListBeli(lstBeli1.getSelectedIndex());
            lstBeli2.setModel(pi.getBeliListModel());
            lstBeli1.setModel(pi.getListModel());
            lblTotPengeluaran.setText("Total pengeluaran : Rp " + pi.getTotalHarga());
            btnPesan.setEnabled(true);
        }        
    }//GEN-LAST:event_btnBeliActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        if(lstBeli2.isSelectionEmpty() == false) {
            pi.removeListBeli(lstBeli2.getSelectedIndex());
            lstBeli2.setModel(pi.getBeliListModel());
            lstBeli1.setModel(pi.getListModel());
            lblTotPengeluaran.setText("Total pengeluaran : Rp " + pi.getTotalHarga());
            if(lstBeli2.getModel().getSize() < 1)
                btnPesan.setEnabled(false);
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void mnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLogOutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login(this, true).setVisible(true);        
    }//GEN-LAST:event_mnLogOutActionPerformed

    private void mnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnExitActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void mnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAboutActionPerformed
        // TODO add your handling code here:
        new About(this, true, "Pembelian").setVisible(true);
    }//GEN-LAST:event_mnAboutActionPerformed

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.YES_OPTION == JOptionPane.showConfirmDialog(this, "Are you sure to but these products?", "Attention", JOptionPane.YES_NO_OPTION)) {
            pi.makingOrder();
            String[] a = new String[0];
            lstBeli2.setListData(a);
            
            try {
                new DocumentMaker().printPembelian();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            } catch (JRException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btnPesanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main("Ita").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBeli;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnPesan;
    private javax.swing.JButton jButton3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblCurrentStocks;
    private javax.swing.JLabel lblEmptyStocks;
    private javax.swing.JLabel lblHello;
    private javax.swing.JLabel lblPurchStatus;
    private javax.swing.JLabel lblTotPengeluaran;
    private javax.swing.JList lstBeli1;
    private javax.swing.JList lstBeli2;
    private javax.swing.JMenuItem mnAbout;
    private javax.swing.JMenuItem mnExit;
    private javax.swing.JMenuItem mnLogOut;
    private javax.swing.JPanel pnlCurrStocks;
    private javax.swing.JPanel pnlEmptyStocks;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlRetur;
    private javax.swing.JTable tblCurrent;
    private javax.swing.JTable tblRetur;
    // End of variables declaration//GEN-END:variables

    /**
     * Fill table with current data
     * from database.
     */
    private void initTable() {
        pi = new PembelianImpl();
        tblCurrent.setModel(pi.getTableModel(CURRENT_STOCK));
        pi.fillTable(tblCurrent, CURRENT_STOCK);
        tblRetur.setModel(pi.getTableModel(RETUR));
        pi.fillTable(tblRetur, RETUR);
    }
    
    /**
     * Change menu interface.
     * 
     * @param option index of menu
     */
    private void changeMenu(int option) {
        if(option == CURRENT_STOCK) {
            pnlCurrStocks.setVisible(true);
            pnlEmptyStocks.setVisible(false);
            pnlRetur.setVisible(false);
        } else if(option == EMPTY_STOCK) {
            pnlCurrStocks.setVisible(false);
            pnlEmptyStocks.setVisible(true);
            pnlRetur.setVisible(false);
        } else if(option == RETUR) {
            pnlCurrStocks.setVisible(false);
            pnlEmptyStocks.setVisible(false);
            pnlRetur.setVisible(true);
        }
    }
    
    
}


